title:    Sara Ranjbar # your name (or website title) here
logo: "/images/cartoon_profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! I am Sara 
  <br><br>
  I use data science and machine learning in clinical imaging research.
  <br><br><br>
  <a href="https://www.linkedin.com/in/sararanjbar-phd/"> <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> </a> 
  <br>
  <a href="https://scholar.google.com/citations?user=vmfTRQ0AAAAJ&hl=en"> src="https://img.shields.io/badge/GoogleScholar-Wenjie_Du-grey?style=flat-square&labelColor=4285F4&logo=googlescholar&logoColor=white" </a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

